uservariables:
  home: absolute path to your home directory
config:
  import_variables:
  - uservariables.yaml:optional
  dotpath: ./
  keepdot: true
dotfiles:
  d_sway:
    src: sway
    dst: ~/.config/sway
  d_waybar:
    src: waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: swaylock
    dst: ~/.config/swaylock
  f_starship.toml:
    src: starship.toml
    dst: ~/.config/starship.toml
  d_neofetch:
    src: neofetch
    dst: ~/.config/neofetch
  d_portage:
    src: portage
    dst: /etc/portage
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  d_greetd:
    src: greetd
    dst: /etc/greetd
  f_discache.timer:
    src: systemd/system/discache.timer
    dst: /etc/systemd/system/discache.timer
  f_discache.service:
    src: systemd/system/discache.service
    dst: /etc/systemd/system/discache.service
  d_user:
    src: systemd/user
    dst: /etc/systemd/user
  d_swayidle:
    src: src/dotfiles/swayidle
    dst: ~/.config/swayidle
  f_foot.ini:
    src: src/dotfiles/foot/foot.ini
    dst: ~/.config/foot/foot.ini
  f_theme.ini:
    src: src/dotfiles/catppuccin/foot/theme.ini
    dst: ~/.config/foot/theme.ini
  f_theme.fish:
    src: src/dotfiles/catppuccin/fish/conf.d/theme.fish
    dst: ~/.config/fish/conf.d/theme.fish
profiles:
  Gentowo:
    dotfiles:
    - d_sway
    - d_waybar
    - d_swaylock
    - d_portage
    - f_fstab
    - d_greetd
    - f_discache.timer
    - f_discache.service
    - d_neofetch
    - f_starship.toml
    - d_user
    - d_swayidle
    - f_foot.ini
  catppuccin:
    dotfiles:
    - f_theme.ini
    - f_theme.fish
