[variables]
etcdir = "/etc"

[dynvariables]
confdir = "echo ${XDG_CONFIG_HOME:-$HOME/.config}"

[config]
dotpath = "./"
keepdot = true

[dotfiles.d_swaylock]
src = "swaylock"
dst = "{{@@ confdir @@}}/swaylock"

[dotfiles."f_starship.toml"]
src = "starship.toml"
dst = "{{@@ confdir @@}}/starship.toml"

[dotfiles.d_neofetch]
src = "neofetch"
dst = "{{@@ confdir @@}}/neofetch"

[dotfiles.d_portage]
src = "portage"
dst = "{{@@ etcdir @@}}/portage"

[dotfiles.d_greetd]
src = "greetd"
dst = "{{@@ etcdir @@}}/greetd"

[dotfiles."f_discache.timer"]
src = "systemd/system/discache.timer"
dst = "{{@@ etcdir @@}}/systemd/system/discache.timer"

[dotfiles."f_discache.service"]
src = "systemd/system/discache.service"
dst = "{{@@ etcdir @@}}/systemd/system/discache.service"

[dotfiles.d_swayidle]
src = "swayidle"
dst = "{{@@ confdir @@}}/swayidle"

[dotfiles."f_foot.ini"]
src = "foot/foot.ini"
dst = "{{@@ confdir @@}}/foot/foot.ini"

[dotfiles."f_foot_catppuccin.ini"]
src = "foot/catppuccin.ini"
dst = "{{@@ confdir @@}}/foot/catppuccin.ini"

[dotfiles."f_fish_catppuccin.fish"]
src = "fish/themes/catppuccin.fish"
dst = "{{@@ confdir @@}}/fish/themes/catppuccin.fish"

[dotfiles.f_sway_config]
src = "sway/config"
dst = "{{@@ confdir @@}}/sway/config"

[dotfiles."f_dotsync.service"]
src = "systemd-user/dotsync.service"
dst = "{{@@ confdir @@}}/systemd/user/dotsync.service"

[dotfiles."f_dotsync.timer"]
src = "systemd-user/dotsync.timer"
dst = "{{@@ confdir @@}}/systemd/user/dotsync.timer"

[dotfiles.d_swappy]
src = "swappy"
dst = "{{@@ confdir @@}}/swappy"

[dotfiles.d_cp_waybar]
src = "catppuccin/waybar"
dst = "{{@@ confdir @@}}/waybar"

[dotfiles.d_systemd_user]
src = "systemd/user"
dst = "{{@@ etcdir @@}}/systemd/user"

[dotfiles.d_rofi]
src = "rofi"
dst = "{{@@ confdir @@}}/rofi"

[dotfiles."f_cp_rofi_theme.rasi"]
src = "catppuccin/rofi/themes/theme.rofi"
dst = "~/.local/share/rofi/themes/theme.rasi"

[profiles.user]
dotfiles = [
  "d_swaylock",
  "d_neofetch",
  "f_starship.toml",
  "d_swayidle",
  "f_foot.ini",
  "f_sway_config",
  "f_dotsync.service",
  "f_dotsync.timer",
  "d_swappy",
  "d_rofi",
]

[profiles.system]
dotfiles = [
  "d_portage",
  "d_greetd",
  "f_discache.timer",
  "f_discache.service",
  "d_systemd_user",
]

[profiles.catppuccin]
dotfiles = [
  "f_cp_foot_theme.ini",
  "f_cp_fish_theme.fish",
  "d_cp_waybar",
  "f_cp_rofi_theme.rasi",
]
