config:
  backup: true
  banner: true
  create: true
  dotpath: ./
  keepdot: true
dotfiles:
  d_portage:
    src: portage
    dst: /etc/portage
  d_bash:
    src: bash
    dst: /etc/bash
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  d_greetd:
    src: greetd
    dst: /etc/greetd
  d_zsh:
    src: zsh
    dst: /etc/zsh
  f_nanorc:
    src: etc/nanorc
    dst: /etc/nanorc
  f_discache.timer:
    src: systemd/system/discache.timer
    dst: /etc/systemd/system/discache.timer
  f_discache.service:
    src: systemd/system/discache.service
    dst: /etc/systemd/system/discache.service
  f_eix-sync.conf:
    src: etc/eix-sync.conf
    dst: /etc/eix-sync.conf
profiles:
  Gentowo:
    dotfiles:
    - d_portage
    - d_bash
    - f_fstab
    - d_greetd
    - d_zsh
    - f_nanorc
    - f_discache.timer
    - f_discache.service
    - f_eix-sync.conf
