uservariables:
  home: "absolute path to your home directory"
config:
  import_variables:
    - uservariables.yaml:optional
  dotpath: ./
  keepdot: true
dotfiles:
  d_alacritty:
    src: alacritty
    dst: {{@@ home @@}}/.config/alacritty
  d_sway:
    src: sway
    dst: /home/weathercold/.config/sway
  d_waybar:
    src: waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: swaylock
    dst: ~/.config/swaylock
  f_starship.toml:
    src: starship.toml
    dst: ~/.config/starship.toml
  d_fish:
    src: fish
    dst: ~/.config/fish
  d_neofetch:
    src: neofetch
    dst: ~/.config/neofetch
  d_portage:
    src: portage
    dst: /etc/portage
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  d_greetd:
    src: greetd
    dst: /etc/greetd
  f_discache.timer:
    src: systemd/system/discache.timer
    dst: /etc/systemd/system/discache.timer
  f_discache.service:
    src: systemd/system/discache.service
    dst: /etc/systemd/system/discache.service
  d_user:
    src: systemd/user
    dst: /etc/systemd/user
profiles:
  Gentowo:
    dotfiles:
    - d_alacritty
    - d_sway
    - d_waybar
    - d_swaylock
    - d_fish
    - d_portage
    - f_fstab
    - d_greetd
    - f_discache.timer
    - f_discache.service
    - d_neofetch
    - f_starship.toml
    - d_user
