[variables]
etcdir = "/etc"

[dynvariables]
confdir = "echo ${XDG_CONFIG_HOME:-$HOME/.config}"

[config]
dotpath = "./"
keepdot = true

[dotfiles.d_swaylock]
src = "swaylock"
dst = "{{@@ confdir @@}}/swaylock"

[dotfiles."f_starship_starship.toml"]
src = "starship.toml"
dst = "{{@@ confdir @@}}/starship.toml"

[dotfiles.d_neofetch]
src = "neofetch"
dst = "{{@@ confdir @@}}/neofetch"

[dotfiles.d_portage]
src = "portage"
dst = "{{@@ etcdir @@}}/portage"

[dotfiles.d_greetd]
src = "greetd"
dst = "{{@@ etcdir @@}}/greetd"

[dotfiles."f_systemd_discache.timer"]
src = "systemd/system/discache.timer"
dst = "{{@@ etcdir @@}}/systemd/system/discache.timer"

[dotfiles."f_systemd_discache.service"]
src = "systemd/system/discache.service"
dst = "{{@@ etcdir @@}}/systemd/system/discache.service"

[dotfiles.d_swayidle]
src = "swayidle"
dst = "{{@@ confdir @@}}/swayidle"

[dotfiles."f_foot_foot.ini"]
src = "foot/foot.ini"
dst = "{{@@ confdir @@}}/foot/foot.ini"

[dotfiles."f_foot_catppuccin.ini"]
src = "foot/catppuccin.ini"
dst = "{{@@ confdir @@}}/foot/catppuccin.ini"

[dotfiles."f_fish_catppuccin.fish"]
src = "fish/themes/catppuccin.fish"
dst = "{{@@ confdir @@}}/fish/themes/catppuccin.fish"

[dotfiles.f_sway_config]
src = "sway/config"
dst = "{{@@ confdir @@}}/sway/config"

[dotfiles.f_sway_catppuccin_config]
src = "sway/catppuccin_config"
dst = "{{@@ confdir @@}}/sway/catppuccin_config"

[dotfiles."f_sway_catppuccin.png"]
src = "sway/catppuccin.png"
dst = "{{@@ confdir @@}}/sway/catppuccin.png"

[dotfiles."f_systemd_dotsync.service"]
src = "systemd/user/dotsync.service"
dst = "{{@@ confdir @@}}/systemd/user/dotsync.service"

[dotfiles."f_systemd_dotsync.timer"]
src = "systemd/user/dotsync.timer"
dst = "{{@@ confdir @@}}/systemd/user/dotsync.timer"

[dotfiles.d_swappy]
src = "swappy"
dst = "{{@@ confdir @@}}/swappy"

[dotfiles.f_waybar_catppuccin_config]
src = "waybar/catppuccin_config"
dst = "{{@@ confdir @@}}/waybar/catppuccin_config"

[dotfiles."f_waybar_catppuccin.css"]
src = "waybar/catppuccin.css"
dst = "{{@@ confdir @@}}/waybar/catppuccin.css"

[dotfiles."f_rofi_config.rasi"]
src = "rofi/config.rasi"
dst = "{{@@ confdir @@}}/rofi/config.rasi"

[dotfiles."f_rofi_catppuccin.rasi"]
src = "rofi/catppuccin.rasi"
dst = "{{@@ confdir @@}}/rofi/catppuccin.rasi"

[dotfiles."f_sway_catppuccin.desktop"]
src = "wayland-sessions/sway_catppuccin.desktop"
dst = "/usr/share/wayland-sessions/sway_catppuccin.desktop"

[dotfiles."f_wayland-session.target"]
src = "systemd/user/wayland-session.target"
dst = "~/.config/systemd/user/wayland-session.target"

[profiles.user]
dotfiles = [ "d_swaylock", "d_neofetch", "f_starship_starship.toml", "d_swayidle", "f_foot_foot.ini", "f_sway_config", "f_systemd_dotsync.service", "f_systemd_dotsync.timer", "d_swappy", "f_rofi_config.rasi", "f_wayland-session.target",]

[profiles.system]
dotfiles = [ "d_portage", "d_greetd", "f_systemd_discache.timer", "f_systemd_discache.service",]

[profiles.catppuccin]
dotfiles = [ "f_sway_catppuccin_config", "f_sway_catppuccin.png", "f_foot_catppuccin.ini", "f_fish_catppuccin.fish", "f_waybar_catppuccin_config", "f_waybar_catppuccin.css", "f_rofi_catppuccin.rasi", "f_sway_catppuccin.desktop",]
