config:
  backup: true
  banner: true
  create: true
  dotpath: ./
  keepdot: true
dotfiles:
  d_alacritty:
    src: alacritty
    dst: ~/.config/alacritty
  d_sway:
    src: sway
    dst: ~/.config/sway
  d_waybar:
    src: waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: swaylock
    dst: ~/.config/swaylock
  f_bashrc:
    src: user/.bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: user/.bash_profile
    dst: ~/.bash_profile
  f_profile:
    src: user/.profile
    dst: ~/.profile
  f_zshrc:
    src: user/.zshrc
    dst: ~/.zshrc
  f_dotsync.timer:
    src: systemd-user/dotsync.timer
    dst: ~/.config/systemd/user/dotsync.timer
  f_dotsync.service:
    src: systemd-user/dotsync.service
    dst: ~/.config/systemd/user/dotsync.service
profiles:
  Gentowo:
    dotfiles:
    - d_alacritty
    - d_sway
    - d_waybar
    - d_swaylock
    - f_bashrc
    - f_bash_profile
    - f_profile
    - f_zshrc
    - f_dotsync.timer
    - f_dotsync.service
