dynvariables:
  confdir: echo ${XDG_CONFIG_HOME:-$HOME/.config}
actions:
  switchtheme: swaymsg -p reload; echo {0} > {{@@ _dotdrop_dotpath @@}}/current_theme
config:
  dotpath: ./
  keepdot: true
dotfiles:
  d_swaylock:
    src: swaylock
    dst: '{{@@ confdir @@}}/swaylock'
  f_starship.toml:
    src: starship.toml
    dst: '{{@@ confdir @@}}/starship.toml'
  d_neofetch:
    src: neofetch
    dst: '{{@@ confdir @@}}/neofetch'
  d_portage:
    src: portage
    dst: /etc/portage
  d_greetd:
    src: greetd
    dst: /etc/greetd
  f_discache.timer:
    src: systemd/system/discache.timer
    dst: /etc/systemd/system/discache.timer
  f_discache.service:
    src: systemd/system/discache.service
    dst: /etc/systemd/system/discache.service
  d_systemd_user:
    src: systemd/user
    dst: /etc/systemd/user
  d_swayidle:
    src: swayidle
    dst: '{{@@ confdir @@}}/swayidle'
  f_foot.ini:
    src: foot/foot.ini
    dst: '{{@@ confdir @@}}/foot/foot.ini'
  f_cp_foot_theme.ini:
    src: catppuccin/foot/theme.ini
    dst: '{{@@ confdir @@}}/foot/theme.ini'
  f_cp_fish_theme.fish:
    src: catppuccin/fish/conf.d/theme.fish
    dst: '{{@@ confdir @@}}/fish/conf.d/theme.fish'
  f_sway_config:
    src: sway/config
    dst: '{{@@ confdir @@}}/sway/config'
  f_dotsync.service:
    src: systemd-user/dotsync.service
    dst: '{{@@ confdir @@}}/systemd/user/dotsync.service'
  f_dotsync.timer:
    src: systemd-user/dotsync.timer
    dst: '{{@@ confdir @@}}/systemd/user/dotsync.timer'
  d_swappy:
    src: swappy
    dst: '{{@@ confdir @@}}/swappy'
  d_cp_waybar:
    src: catppuccin/waybar
    dst: '{{@@ confdir @@}}/waybar'
  d_al_waybar:
    src: ayu-light/waybar
    dst: '{{@@ confdir @@}}/waybar'
profiles:
  user:
    dotfiles:
    - d_swaylock
    - d_neofetch
    - f_starship.toml
    - d_swayidle
    - f_foot.ini
    - f_sway_config
    - f_dotsync.service
    - f_dotsync.timer
    - d_swappy
  system:
    dotfiles:
    - d_portage
    - d_greetd
    - f_discache.timer
    - f_discache.service
    - d_systemd_user
  catppuccin:
    actions:
    - switchtheme catppuccin
    dotfiles:
    - f_cp_foot_theme.ini
    - f_cp_fish_theme.fish
    - d_cp_waybar
  ayu-light:
    actions:
    - switchtheme ayu-light
    dotfiles:
    - d_al_waybar
