config:
  backup: true
  banner: true
  create: true
  dotpath: ./
  keepdot: true
dotfiles:
  d_alacritty:
    src: alacritty
    dst: ~/.config/alacritty
  d_sway:
    src: sway
    dst: ~/.config/sway
  d_waybar:
    src: waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: swaylock
    dst: ~/.config/swaylock
  f_dotsync.timer:
    src: systemd-user/dotsync.timer
    dst: ~/.config/systemd/user/dotsync.timer
  f_dotsync.service:
    src: systemd-user/dotsync.service
    dst: ~/.config/systemd/user/dotsync.service
  f_starship.toml:
    src: starship.toml
    dst: ~/.config/starship.toml
  d_fish:
    src: fish
    dst: ~/.config/fish
    chmod: '700'
  d_neofetch:
    src: neofetch
    dst: ~/.config/neofetch
profiles:
  Gentowo:
    dotfiles:
    - d_alacritty
    - d_sway
    - d_waybar
    - d_swaylock
    - f_dotsync.timer
    - f_dotsync.service
    - f_starship.toml
    - d_fish
    - d_neofetch
